### ISSUE TITLE
Refactor plugin to prevent overpaying players with infinite cash

### ISSUE THREAD

**Issue by EDGRRRRs** [EDGRRRRs/DCE#40]
Plugin should not let users have infinite cash!
This happens with setbal and so on.
/sell should factor in having infinite cash.

**Comment by EDGRRRRs** [comment]
I have updated some methods to provide an error once this happens.
Refactoring the code to undo all previous operations for something rare like this... no.

**Comment by RyanA3** [comment]
How is accidentally paying infinite cash possible?

**Comment by EDGRRRRs** [comment]
Not actually sure, it seems to be caused by players or items having more or being worth more than what a double can store.

**Comment by EDGRRRRs** [comment]
> How is accidentally paying infinite cash possible?

Not actually sure, it seems to be caused by players or items having more or being worth more than what a double can store.

**Comment by EDGRRRRs** [comment]
This may be fixed in the latest pull request from the economy update.

**Comment by EDGRRRRs** [comment]
With the BigDecimal update. This should no longer happen. As not only can we support larger values with increased accuracy. But also any values above what's possible should be rejected and refunded (should it be an item sale, for example).
